using Programming_Patterns.Factory.Enums;
using Programming_Patterns.Shared;
using System.Text;

namespace Programming_Patterns.Factory.Models
{
    public class Membership
    {
        [Printable("Membership")]
        public MembershipType Type { get; internal set; }

        [Printable("ID")]
        public Guid Id { get; }

        [Printable("Owner")]
        public string OwnerName { get; set; }

        [Printable("Created")]
        public DateTime Created { get; }

        [Printable("Expiry")]
        public DateTime Expiry { get; set; }

        [Printable("Has Access to the Pool?")]
        public bool AccessToPool { get; internal set; }

        [Printable("Yearly Gift Benefits?")]
        public bool RightToYearlyGift { get; internal set; }

        [Printable("Discount", unit: "%")]
        public float DiscountPercentage { get; internal set; }

        public Membership(string UserName)
        {
            Id = Guid.NewGuid();
            Created = DateTime.Now;
            OwnerName = UserName;
        }

        public override string ToString() =>
            new DataClassPrinter<Membership>(this, "Membership").AutoGeneratedescription();

        // private static string AddAttributeDescription(string label, string data) =>
        //     new StringBuilder().Append(label).Append(": ").AppendLine(data).ToString();
    }
}
